#!/bin/bash
#
# 03-network-stack — optionally rename NICs by MAC for stable names
# (eth-lan, eth-diretta), then let the user choose between keeping
# NetworkManager (tuned) or switching to systemd-networkd.
#
# Step 1: stable interface naming (opt-in, default Y). Writes
# /etc/systemd/network/10-{lan,diretta}.link drop-ins matched by MAC, which
# rename the NICs at next boot regardless of PCI topology (NIC swap, added
# PCIe card, GPU insert/remove on hosts without iGPU). Stack-agnostic —
# udev applies .link files BEFORE NM or networkd starts.
#
# Step 2: network stack choice. Default keep NetworkManager (safe for SSH
# hosts, supports nmtui). systemd-networkd is offered as an opt-in for
# users who observe playback dropouts (Qobuz on some hardware) or want a
# fully deterministic stack. State-aware: if already on networkd and user
# picks "keep NM", the previous switch is reverted (re-enable NM, disable
# networkd, remove tagged .network files and the wait-online drop-in).
#
# If stable naming was set up in step 1, the networkd branch generates
# .network files matching the stable names (eth-lan/eth-diretta) so they
# keep matching after the next-boot rename — single coherent reboot.
#
# Files this module generates carry a header line so the revert can
# identify them safely without touching .network files the user wrote by
# hand.
#

set -euo pipefail

readonly _NET_GEN_TAG="# Generated by fedora-audiophile-setup"
readonly _NET_DIR="/etc/systemd/network"
readonly _NET_WAIT_DROPIN_DIR="/etc/systemd/system/systemd-networkd-wait-online.service.d"
readonly _NET_WAIT_DROPIN="${_NET_WAIT_DROPIN_DIR}/10-limit-to-wan.conf"

# Stable-naming step (see _net_stable_naming_step below) populates this map:
# key = current kernel-assigned name (enpXsY), value = stable name (eth-lan,
# eth-diretta). Used by the networkd branch to write .network files that
# match the post-rename names instead of the volatile enpXsY ones.
declare -gA _NET_STABLE_MAP=()

log_step "Network stack: NetworkManager (tuned) or systemd-networkd"

# --- State detection ------------------------------------------------------

_net_current_stack() {
    local nm netd
    is_service_active NetworkManager     && nm=1   || nm=0
    is_service_active systemd-networkd   && netd=1 || netd=0
    if   [[ $nm -eq 1 && $netd -eq 0 ]]; then echo "NetworkManager"
    elif [[ $nm -eq 0 && $netd -eq 1 ]]; then echo "systemd-networkd"
    elif [[ $nm -eq 1 && $netd -eq 1 ]]; then echo "both"
    else                                       echo "none"
    fi
}

_net_detect_wan_iface() {
    ip -o -4 route show default 2>/dev/null | awk '{print $5; exit}'
}

# Print one iface per line: physical, ethernet (type 1), not lo. We include
# operstate-down NICs here too, because at install time the Diretta target may
# be powered off (no carrier on the Diretta NIC); we still want to be able to
# assign it a stable name.
_net_physical_ethernet_ifaces() {
    local sys iface typ
    for sys in /sys/class/net/*; do
        iface=$(basename "$sys")
        [[ "$iface" == "lo" ]] && continue
        [[ "$(readlink -f "$sys")" == *"/devices/virtual/"* ]] && continue
        # Skip wireless interfaces: wlan0 reports type 1 (ARPHRD_ETHER) like
        # ethernet, but the wizard manages only wired NICs — renaming wifi to
        # eth-* is meaningless, and counting it breaks the 2-NIC LAN/Diretta
        # auto-detect on a Pi with wifi on (the default). Reported via Progman.
        [[ -e "${sys}/phy80211" || -d "${sys}/wireless" ]] && continue
        typ=$(cat "${sys}/type" 2>/dev/null || echo "")
        [[ "$typ" == "1" ]] || continue
        echo "$iface"
    done
}

# --- Stable naming step (MAC-based .link rename) --------------------------
#
# Why: PCI bus enumeration is unstable across hardware changes — NIC swap,
# added PCIe card, inserted/removed GPU on hosts without iGPU. Any config
# that references the kernel-assigned name (enpXsY) silently breaks when
# the topology changes. The fix is a one-time rename, by MAC address, to
# stable names (eth-lan, eth-diretta) via systemd-udevd .link drop-ins.
#
# This step is stack-agnostic — .link files are processed by udev BEFORE
# either NetworkManager or systemd-networkd starts, so the rename applies
# regardless of which network manager is active. The networkd branch in
# this module reads _NET_STABLE_MAP to generate .network files matching
# the stable names (so they keep matching after the next-boot rename).
# The NetworkManager branch only writes the .link files and warns the
# user to update their NM connections to use eth-lan after reboot.
#
# Match by MAC + Type=ether: MAC survives PCI re-enumeration, Type=ether
# excludes virtual interfaces (notably the bridge that diretta-net-toggle
# creates by cloning the LAN MAC onto br0 — without Type=ether a MAC-only
# rule would be ambiguous).

_net_pick_iface() {
    local prompt="$1"; shift
    local -a opts=("$@")
    local i choice
    echo
    echo "${prompt}"
    for i in "${!opts[@]}"; do
        printf "  %d) %s\n" "$((i+1))" "${opts[$i]}"
    done
    while true; do
        read -r -p "Choose [1-${#opts[@]}]: " choice
        if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#opts[@]} )); then
            echo "${opts[$((choice-1))]}"
            return 0
        fi
    done
}

_net_write_stable_link() {
    local iface="$1" role="$2" stable_name="$3"
    local link_file="${_NET_DIR}/10-${role}.link"
    local mac
    mac=$(cat "/sys/class/net/${iface}/address" 2>/dev/null || true)
    if [[ -z "$mac" ]]; then
        log_warn "Could not read MAC for ${iface} — skipping ${link_file}."
        return 1
    fi
    log_info "Writing ${link_file}: MAC ${mac} → ${stable_name}"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${link_file}"
        return 0
    fi
    mkdir -p "$_NET_DIR"
    cat > "$link_file" <<EOF
${_NET_GEN_TAG}
# Stable name for the ${role} NIC, matched by MAC address (survives PCI
# re-enumeration: NIC swap, GPU insert/remove, added PCIe card). Type=ether
# excludes virtual interfaces — required because diretta-net-toggle creates
# a bridge that clones the LAN MAC, and a MAC-only rule would match both
# the physical NIC and the bridge.
[Match]
MACAddress=${mac}
Type=ether

[Link]
Name=${stable_name}
EOF
}

_net_stable_naming_step() {
    echo
    log_info "Stable interface naming (by MAC) — optional"
    log_info "  Renames NICs from PCI-volatile names (enpXsY) to stable names"
    log_info "  (eth-lan, eth-diretta) that survive NIC swaps, GPU insert/remove,"
    log_info "  added PCIe cards. Applied by udev at next boot."
    log_info "  Works under both NetworkManager and systemd-networkd."
    if ! ask_yes_no "Set up stable names by MAC?" Y; then
        log_info "Skipping stable naming — interface names will remain PCI-volatile."
        return 0
    fi

    local -a ifaces=()
    while IFS= read -r i; do ifaces+=("$i"); done < <(_net_physical_ethernet_ifaces)
    if [[ ${#ifaces[@]} -eq 0 ]]; then
        log_warn "No physical ethernet NICs detected — cannot set up stable names."
        return 0
    fi
    if [[ ${#ifaces[@]} -eq 1 ]]; then
        log_info "Only one NIC detected: ${ifaces[0]} will be renamed eth-lan."
        if ask_yes_no "Confirm?" Y; then
            _net_write_stable_link "${ifaces[0]}" "lan" "eth-lan" && _NET_STABLE_MAP["${ifaces[0]}"]="eth-lan"
            _net_stable_naming_finalize
        fi
        return 0
    fi

    # Auto-detect LAN (default-route iface) and Diretta (the other, if exactly 2 NICs).
    local lan_iface diretta_iface=""
    lan_iface=$(_net_detect_wan_iface)
    if [[ ${#ifaces[@]} -eq 2 ]]; then
        local i
        for i in "${ifaces[@]}"; do
            [[ "$i" != "$lan_iface" ]] && diretta_iface="$i"
        done
    fi

    echo
    echo "Detected interfaces (current name + MAC):"
    local m
    for i in "${ifaces[@]}"; do
        m=$(cat "/sys/class/net/${i}/address" 2>/dev/null || echo "?")
        printf "  %-12s %s\n" "$i" "$m"
    done
    echo
    echo "Auto-detected roles:"
    printf "  LAN     : %-12s → will be renamed eth-lan\n"     "${lan_iface:-<not detected>}"
    printf "  Diretta : %-12s → will be renamed eth-diretta\n" "${diretta_iface:-<not detected>}"

    if ! ask_yes_no "Use these roles?" Y; then
        lan_iface=$(_net_pick_iface "Which NIC is LAN (connected to router/internet)?" "${ifaces[@]}")
        local -a rest=()
        for i in "${ifaces[@]}"; do
            [[ "$i" != "$lan_iface" ]] && rest+=("$i")
        done
        if [[ ${#rest[@]} -eq 1 ]]; then
            diretta_iface="${rest[0]}"
        elif [[ ${#rest[@]} -gt 1 ]]; then
            diretta_iface=$(_net_pick_iface "Which NIC is connected to the Diretta target? (or last option = skip)" "${rest[@]}" "(skip — no Diretta rename)")
            [[ "$diretta_iface" == "(skip — no Diretta rename)" ]] && diretta_iface=""
        fi
    fi

    if [[ -n "$lan_iface" ]]; then
        _net_write_stable_link "$lan_iface" "lan" "eth-lan" && _NET_STABLE_MAP["$lan_iface"]="eth-lan"
    fi
    if [[ -n "$diretta_iface" ]]; then
        _net_write_stable_link "$diretta_iface" "diretta" "eth-diretta" && _NET_STABLE_MAP["$diretta_iface"]="eth-diretta"
    fi

    _net_stable_naming_finalize
}

_net_stable_naming_finalize() {
    log_info "Refreshing initramfs (dracut -f) so the rename applies at next boot."
    run_cmd dracut -f
    log_warn "Stable names will take effect at the NEXT BOOT."
    log_warn "Anything that hard-codes the old PCI name (NM connections, /etc/default/diretta-renderer, /etc/default/slim2diretta, diretta-net-toggle state, etc.) must be updated to 'eth-lan' / 'eth-diretta' — modules 10/11 do this automatically when re-run; NetworkManager connections must be edited manually (sudo nmtui, or 'sudo nmcli connection modify <name> connection.interface-name eth-lan')."
}

# --- Branch K: keep / restore NetworkManager (tuned) ----------------------

_net_revert_to_nm() {
    log_warn "Reverting previous switch: re-enabling NetworkManager, disabling systemd-networkd."
    run_cmd systemctl unmask NetworkManager
    run_cmd systemctl enable --now NetworkManager
    run_cmd systemctl disable --now systemd-networkd
    run_cmd systemctl disable --now systemd-networkd-wait-online.socket || true
    run_cmd systemctl disable --now systemd-networkd-wait-online.service || true

    # Remove only the .network files we generated (tagged in header).
    if [[ -d "$_NET_DIR" ]]; then
        local f
        while IFS= read -r f; do
            if head -1 "$f" 2>/dev/null | grep -qF "$_NET_GEN_TAG"; then
                log_info "Removing generated ${f}"
                run_cmd rm -f "$f"
            fi
        done < <(find "$_NET_DIR" -maxdepth 1 -name '*.network' -type f 2>/dev/null)
    fi

    if [[ -f "$_NET_WAIT_DROPIN" ]]; then
        run_cmd rm -f "$_NET_WAIT_DROPIN"
        rmdir --ignore-fail-on-non-empty "$_NET_WAIT_DROPIN_DIR" 2>/dev/null || true
    fi
    run_cmd systemctl daemon-reload
}

_net_tune_nm() {
    if ! has_package NetworkManager-tui; then
        log_info "Installing NetworkManager-tui (provides nmtui)."
        run_cmd dnf -y install NetworkManager-tui
    fi
    if is_service_enabled NetworkManager-wait-online.service; then
        log_info "Disabling NetworkManager-wait-online.service (avoids boot delays)."
        run_cmd systemctl disable NetworkManager-wait-online.service
    fi
}

_net_keep_nm() {
    local current="$1"
    case "$current" in
        systemd-networkd|both) _net_revert_to_nm ;;
        none)                  run_cmd systemctl enable --now NetworkManager ;;
        NetworkManager)        : ;;  # already there
    esac
    _net_tune_nm
    log_info "Network stack: NetworkManager (tuned)."
}

# --- Branch S: switch to systemd-networkd ---------------------------------

# <name> is the name to use in both the filename and the [Match] Name= line.
# If stable-naming was set up for this iface, callers pass the stable name
# (eth-lan, eth-diretta) so the .network keeps matching after the rename
# takes effect at next boot. Otherwise the current PCI name is used.
_net_write_dhcp_network() {
    local name="$1" file="${_NET_DIR}/10-${name}.network"
    log_info "Generating ${file} (DHCP, matches Name=${name})"
    cat > "$file" <<EOF
${_NET_GEN_TAG}
[Match]
Name=${name}

[Network]
DHCP=yes
EOF
}

_net_write_static_network() {
    local name="$1" addr="$2" gw="$3"
    local file="${_NET_DIR}/10-${name}.network"
    log_info "Generating ${file} (static ${addr}${gw:+, gw=${gw}}, matches Name=${name})"
    {
        echo "${_NET_GEN_TAG}"
        echo "[Match]"
        echo "Name=${name}"
        echo
        echo "[Network]"
        [[ -n "$addr" ]] && echo "Address=${addr}"
        [[ -n "$gw" ]]   && echo "Gateway=${gw}"
    } > "$file"
}

_net_generate_network_files() {
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would generate one .network file per active physical ethernet interface under ${_NET_DIR}"
        return 0
    fi
    mkdir -p "$_NET_DIR"
    local iface name method addr gw
    while IFS= read -r iface; do
        # If stable-naming was set up for this iface, use the stable name so
        # the .network keeps matching after the next-boot rename.
        name="${_NET_STABLE_MAP[$iface]:-$iface}"
        method=$(nmcli -t -f IPV4.METHOD device show "$iface" 2>/dev/null | cut -d: -f2 | head -1 || true)
        case "$method" in
            auto|"")
                _net_write_dhcp_network "$name"
                ;;
            manual)
                addr=$(nmcli -t -f IP4.ADDRESS device show "$iface" 2>/dev/null | cut -d: -f2 | head -1)
                gw=$(nmcli -t -f IP4.GATEWAY device show "$iface" 2>/dev/null | cut -d: -f2 | head -1)
                _net_write_static_network "$name" "$addr" "$gw"
                ;;
            *)
                log_warn "Skipping interface ${iface}: NM IPv4 method '${method}' not supported in v0.1. Configure ${_NET_DIR}/10-${name}.network manually."
                ;;
        esac
    done < <(_net_physical_ethernet_ifaces)
}

_net_limit_wait_online() {
    local wan
    wan=$(_net_detect_wan_iface)
    if [[ -z "$wan" ]]; then
        log_warn "Could not detect WAN interface (no default route). Skipping networkd-wait-online limit."
        return 0
    fi
    log_info "Limiting systemd-networkd-wait-online to ${wan}"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${_NET_WAIT_DROPIN}"
        return 0
    fi
    mkdir -p "$_NET_WAIT_DROPIN_DIR"
    cat > "$_NET_WAIT_DROPIN" <<EOF
${_NET_GEN_TAG}
[Service]
ExecStart=
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online -i ${wan}
EOF
    run_cmd systemctl daemon-reload
}

_net_switch_to_networkd() {
    local current="$1"
    if [[ "$current" == "systemd-networkd" ]]; then
        log_info "Already on systemd-networkd — re-generating config if needed."
    fi

    log_warn "Switching from NetworkManager to systemd-networkd."
    log_warn "If your generated config is wrong you may LOSE NETWORK ACCESS — make sure you have console (not just SSH) access before continuing."
    if ! ask_yes_no "Continue?" N; then
        log_info "Aborted by user — leaving the network stack untouched."
        return 0
    fi

    _net_generate_network_files
    _net_limit_wait_online

    run_cmd systemctl enable --now systemd-networkd
    run_cmd systemctl enable --now systemd-resolved
    if [[ "$current" != "none" ]]; then
        run_cmd systemctl disable --now NetworkManager
        run_cmd systemctl mask NetworkManager
    fi
    log_info "Network stack: systemd-networkd."
}

# --- Dispatch -------------------------------------------------------------

_current_stack=$(_net_current_stack)
log_info "Detected current network stack: ${_current_stack}"

if [[ "$_current_stack" == "both" ]]; then
    log_warn "Both NetworkManager and systemd-networkd are active — this is a broken state. The module will resolve it based on your choice below."
fi

# Step 1: optional stable-naming by MAC (stack-agnostic — writes .link files
# read by udev before either NM or networkd starts). Populates _NET_STABLE_MAP
# so the networkd branch can write .network files matching the post-rename
# names instead of the volatile PCI names.
_net_stable_naming_step

# Step 2: choose the network management stack.
echo
echo "Network stack options:"
echo "  K) Keep NetworkManager (tuned)   [default — safe, supports nmtui]"
echo "  S) Switch to systemd-networkd    [deterministic, opt-in]"
echo "  N) Skip — do not touch the network stack"
echo
read -r -p "Choose [K/s/n] " _choice
_choice="${_choice:-K}"

case "${_choice^^}" in
    K) _net_keep_nm "$_current_stack" ;;
    S) _net_switch_to_networkd "$_current_stack" ;;
    N) log_info "Skipping — network stack left as-is." ;;
    *) log_error "Invalid choice: ${_choice}"; exit 1 ;;
esac
