#!/bin/bash
#
# 06-cpu-states — pin CPU to performance, disable turbo/boost, disable
# deep idle states, optionally cap the max CPU frequency, and apply
# audio-friendly memory/MM tunings.
#
# Installs a single systemd oneshot service that on every boot writes to
# /sys/... to:
#   1. Set scaling_governor=performance on every CPU
#   2. Disable turbo/boost (Intel pstate no_turbo, or generic cpufreq boost)
#   3. (optional) Cap the max CPU frequency to N% of the hardware max,
#      configurable via /etc/default/audiophile-cpu-states (CPU_MAX_PCT=…).
#      Audiophile lore: lower peak current draw = less electrical noise on
#      the DAC analog rail (subjective; try 50/75/100 and decide).
#   4. Disable c-states deeper than C0/C1 on every CPU
#   5. Memory/MM jitter reducers — disable Transparent Huge Pages (no
#      periodic khugepaged scan), Kernel Samepage Merging (no periodic
#      page-merge scan), and NUMA balancing (no async page migration).
#      Best-effort: missing sysfs nodes skipped silently.
#
# The CPU_MAX_PCT value can be re-tuned WITHOUT re-running the wizard:
# just edit /etc/default/audiophile-cpu-states and
# `sudo systemctl restart audiophile-cpu-states.service`.
#
# Independent of the DRUP tuner — both can coexist safely (they write the
# same values). Idempotent: re-running rewrites the service / script and
# restarts the unit so the latest content is applied immediately.
#
# Arch-agnostic: the boot script is best-effort, so it runs unchanged on
# x86_64 (Intel/AMD) and on ARM aarch64 (Raspberry Pi 5, cpufreq-dt) — the
# Intel-only knobs (no_turbo, max_perf_pct) fall through to generic cpufreq
# paths when absent. See the per-step notes in the generated script below.
#

set -euo pipefail

readonly _CPU_GEN_TAG="# Generated by fedora-audiophile-setup"
readonly _CPU_SERVICE="audiophile-cpu-states.service"
readonly _CPU_SERVICE_PATH="/etc/systemd/system/${_CPU_SERVICE}"
readonly _CPU_SCRIPT="/usr/local/sbin/audiophile-cpu-states.sh"
readonly _CPU_CONF="/etc/default/audiophile-cpu-states"

log_step "CPU performance pinning (governor / no-turbo-boost / max-freq cap / c-states / memory tunings)"

# Read current CPU_MAX_PCT from the conf file (if any), then prompt to
# set/keep/disable a cap and rewrite the file.
_cpu_write_conf() {
    local current=""
    if [[ -r "$_CPU_CONF" ]]; then
        current=$(grep -E '^CPU_MAX_PCT=' "$_CPU_CONF" 2>/dev/null | tail -1 | cut -d= -f2 | tr -d ' ')
    fi

    local pct="" suggested=""
    if [[ -n "$current" ]]; then
        log_info "Current CPU max-freq cap: ${current}% (from ${_CPU_CONF})."
        if ask_yes_no "Keep capping the CPU max frequency?" Y; then
            suggested="$current"
        fi
    else
        log_info "Optional: cap the CPU max frequency. Lower peak frequency draws less current — many audiophile users find this lowers perceived electrical noise on the DAC analog rail (subjective). Diretta itself needs very little CPU, so there is ample headroom."
        if ask_yes_no "Cap the CPU max frequency? (opt-in)" N; then
            suggested="50"
        fi
    fi

    if [[ -n "$suggested" ]]; then
        while true; do
            read -r -p "Cap percent [1-100, default ${suggested}]: " pct
            pct="${pct:-$suggested}"
            if [[ "$pct" =~ ^([1-9][0-9]?|100)$ ]]; then
                break
            fi
            echo "Invalid: enter an integer between 1 and 100."
        done
    fi

    log_info "Writing ${_CPU_CONF} (CPU_MAX_PCT=${pct:-<unset>})"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${_CPU_CONF}"
        return 0
    fi
    cat > "$_CPU_CONF" <<EOF
${_CPU_GEN_TAG}
# Configuration for audiophile-cpu-states.service.
# Edit then: sudo systemctl restart audiophile-cpu-states.service
# (or: sudo ./setup.sh --only cpu-states  to re-prompt the wizard.)
#
# Cap the CPU max frequency to this percent of the hardware max (1-100).
# Empty/unset = no cap. Boost/Turbo is disabled by the service regardless;
# this only LOWERS the max. Audiophile lore: less peak current = less
# electrical noise on the DAC analog rail (subjective — try 50/75/100).
CPU_MAX_PCT=${pct}
EOF
}

_cpu_write_script() {
    log_info "Installing ${_CPU_SCRIPT}"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${_CPU_SCRIPT}"
        return 0
    fi
    mkdir -p "$(dirname "$_CPU_SCRIPT")"
    cat > "$_CPU_SCRIPT" <<'SCRIPT_EOF'
#!/bin/bash
# Generated by fedora-audiophile-setup — boot-time CPU tuning.
# Best-effort: missing sysfs nodes are skipped silently, so the same script
# runs unchanged on x86_64 (Intel pstate, AMD pstate, acpi-cpufreq) and on
# ARM aarch64 (Raspberry Pi 5, cpufreq-dt). The Intel-only knobs simply fall
# through to the generic cpufreq paths when they're absent.

set -u

# Optional configuration (CPU_MAX_PCT).
[[ -r /etc/default/audiophile-cpu-states ]] && . /etc/default/audiophile-cpu-states

# 1. Governor = performance on every CPU
for f in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    [[ -w "$f" ]] && echo performance > "$f" 2>/dev/null || true
done

# 2. Disable turbo / boost. Intel pstate exposes no_turbo; everything else
#    (AMD pstate, acpi-cpufreq) exposes cpufreq/boost. On ARM (Pi 5) neither
#    exists — there is no separate runtime boost knob, so this is a no-op and
#    governor=performance (step 1) is what pins the clock to the top OPP.
if [[ -w /sys/devices/system/cpu/intel_pstate/no_turbo ]]; then
    echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo 2>/dev/null || true
elif [[ -w /sys/devices/system/cpu/cpufreq/boost ]]; then
    echo 0 > /sys/devices/system/cpu/cpufreq/boost 2>/dev/null || true
fi

# 3. Optional: cap the max CPU frequency.
#    Intel pstate: use max_perf_pct (a percent of the platform max).
#    Otherwise (AMD pstate, acpi-cpufreq, ARM cpufreq-dt): write
#    scaling_max_freq per CPU, computed from the per-CPU cpuinfo_max_freq.
#    On the Pi 5 the 4 cores share one clock policy; writing each is fine,
#    and the cpufreq core clamps the request to the nearest available OPP.
if [[ -n "${CPU_MAX_PCT:-}" ]] && [[ "$CPU_MAX_PCT" =~ ^[0-9]+$ ]] \
        && (( CPU_MAX_PCT >= 1 && CPU_MAX_PCT <= 100 )); then
    if [[ -w /sys/devices/system/cpu/intel_pstate/max_perf_pct ]]; then
        echo "$CPU_MAX_PCT" > /sys/devices/system/cpu/intel_pstate/max_perf_pct 2>/dev/null || true
    else
        for cpu in /sys/devices/system/cpu/cpu[0-9]*/cpufreq; do
            [[ -d "$cpu" ]] || continue
            max_hz=$(cat "$cpu/cpuinfo_max_freq" 2>/dev/null) || continue
            [[ -n "$max_hz" ]] || continue
            new_hz=$(( max_hz * CPU_MAX_PCT / 100 ))
            echo "$new_hz" > "$cpu/scaling_max_freq" 2>/dev/null || true
        done
    fi
fi

# 4. Disable c-states deeper than C0/C1 (state2 and beyond)
for d in /sys/devices/system/cpu/cpu*/cpuidle; do
    [[ -d "$d" ]] || continue
    for s in "$d"/state[2-9]*; do
        [[ -w "$s/disable" ]] && echo 1 > "$s/disable" 2>/dev/null || true
    done
done

# 5. Memory / MM tunings — remove sources of background MM jitter.
#    a) Transparent Huge Pages: no periodic khugepaged scan/defrag.
for f in /sys/kernel/mm/transparent_hugepage/enabled \
         /sys/kernel/mm/transparent_hugepage/defrag; do
    [[ -w "$f" ]] && echo never > "$f" 2>/dev/null || true
done
#    b) Kernel Samepage Merging: no periodic page-merge scan.
[[ -w /sys/kernel/mm/ksm/run ]] && echo 0 > /sys/kernel/mm/ksm/run 2>/dev/null || true
#    c) NUMA balancing: no async kernel page migration between nodes.
[[ -w /proc/sys/kernel/numa_balancing ]] && echo 0 > /proc/sys/kernel/numa_balancing 2>/dev/null || true

exit 0
SCRIPT_EOF
    chmod +x "$_CPU_SCRIPT"
}

_cpu_write_service() {
    log_info "Installing ${_CPU_SERVICE_PATH}"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${_CPU_SERVICE_PATH}"
        return 0
    fi
    cat > "$_CPU_SERVICE_PATH" <<EOF
${_CPU_GEN_TAG}
[Unit]
Description=Audiophile CPU performance pinning (governor, no_turbo, max-freq cap, c-states, memory tunings)
After=multi-user.target

[Service]
Type=oneshot
EnvironmentFile=-${_CPU_CONF}
ExecStart=${_CPU_SCRIPT}
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
}

_cpu_write_conf
_cpu_write_script
_cpu_write_service
run_cmd systemctl daemon-reload
run_cmd systemctl enable "$_CPU_SERVICE"
# Use restart (not start) so a re-run after editing the script picks up the
# new content even when the unit is already active with RemainAfterExit=yes.
run_cmd systemctl restart "$_CPU_SERVICE"

log_info "CPU performance pinning service installed and active."
log_info "To experiment with a different max-freq cap: edit ${_CPU_CONF} (CPU_MAX_PCT=…), then 'sudo systemctl restart ${_CPU_SERVICE}'."
