#!/bin/bash
#
# 09-swap-disable — turn swap off on an audiophile playback host.
#
# Four steps:
#   0. Disable Fedora's zram-generator              (empty conf + mask unit —
#      otherwise /dev/zram0 swap is re-created every boot, outside fstab)
#   1. swapoff -a                                   (runtime, immediate)
#   2. vm.swappiness = 0 in /etc/sysctl.d/          (belt-and-braces — has
#      no effect when no swap exists, but if someone re-enables swap by
#      accident, the kernel still won't reach for it under normal load)
#   3. Comment out swap entries in /etc/fstab       (persistent across reboot)
#
# Idempotent: /proc/swaps is probed before swapoff; the sysctl file is
# rewritten with the same content; fstab swap lines are tagged when
# commented so re-runs are no-ops. fstab is backed up before edit.
#

set -euo pipefail

readonly _SWAP_GEN_TAG="# Generated by fedora-audiophile-setup"
readonly _SWAP_FSTAB_TAG="# audiophile-setup disabled: "
readonly _SWAP_SYSCTL_FILE="/etc/sysctl.d/99-audiophile-swap.conf"
readonly _SWAP_FSTAB="/etc/fstab"
readonly _ZRAM_CONF="/etc/systemd/zram-generator.conf"

log_step "Disable swap (runtime + persistent)"

# --- 0. zram-generator: stop Fedora re-creating swap on reboot -----------
#
# Fedora ships zram-generator, which at every boot creates a compressed swap
# device (/dev/zram0) via systemd-zram-setup@zram0.service — entirely outside
# /etc/fstab. The runtime swapoff in step 1 clears it now, but the generator
# re-creates it on the next boot, so without this step swap silently returns.
# The documented way to disable it is an empty /etc/systemd/zram-generator.conf
# (overrides the /usr/lib default → no [zram0] section → no device); we also
# mask the unit so it can't start in the current session. Idempotent (mask and
# truncate are no-ops on re-run); a no-op when zram-generator isn't installed.
_zram_unit="systemd-zram-setup@zram0.service"
if rpm -q zram-generator >/dev/null 2>&1; then
    log_info "zram-generator present — disabling zram swap (empty ${_ZRAM_CONF} + mask ${_zram_unit})."
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would create empty ${_ZRAM_CONF}, then stop and mask ${_zram_unit}."
    else
        : > "$_ZRAM_CONF"
        run_cmd systemctl stop "$_zram_unit" || true
        run_cmd systemctl mask "$_zram_unit"
        log_info "zram swap disabled (persists across reboot via the empty ${_ZRAM_CONF})."
    fi
else
    log_info "zram-generator not installed — no zram swap to disable."
fi

# --- 1. runtime swapoff --------------------------------------------------

_swap_active() {
    awk 'NR > 1 {f=1} END {exit !f}' /proc/swaps
}

if _swap_active; then
    log_info "Disabling all active swap (swapoff -a)"
    run_cmd swapoff -a
else
    log_info "No swap currently active — skipping swapoff."
fi

# --- 2. vm.swappiness = 0 ------------------------------------------------

if [[ -f "$_SWAP_SYSCTL_FILE" ]] && grep -q '^vm.swappiness *= *0' "$_SWAP_SYSCTL_FILE"; then
    log_info "${_SWAP_SYSCTL_FILE} already sets vm.swappiness=0 — skipping."
else
    log_info "Writing ${_SWAP_SYSCTL_FILE} (vm.swappiness=0)"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${_SWAP_SYSCTL_FILE} and run 'sysctl --system'"
    else
        cat > "$_SWAP_SYSCTL_FILE" <<EOF
${_SWAP_GEN_TAG}
vm.swappiness = 0
EOF
        run_cmd sysctl --system
    fi
fi

# --- 3. fstab: comment out swap entries ----------------------------------

_swap_fstab_has_active_swap_line() {
    awk '/^[[:space:]]*#/ {next} NF >= 3 && $3 == "swap" {f=1} END {exit !f}' "$_SWAP_FSTAB"
}

if _swap_fstab_has_active_swap_line; then
    log_info "Commenting out swap entries in ${_SWAP_FSTAB}"
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would back up ${_SWAP_FSTAB} and comment swap lines."
    else
        cp -a "$_SWAP_FSTAB" "${_SWAP_FSTAB}.audiophile-bak.$(date +%s)"
        awk -v tag="$_SWAP_FSTAB_TAG" '
            /^[[:space:]]*#/ { print; next }
            NF >= 3 && $3 == "swap" { print tag $0; next }
            { print }
        ' "$_SWAP_FSTAB" > "${_SWAP_FSTAB}.new"
        mv "${_SWAP_FSTAB}.new" "$_SWAP_FSTAB"
    fi
else
    log_info "No active swap entries in ${_SWAP_FSTAB} — skipping."
fi

log_info "Swap disabled (runtime, sysctl, fstab)."
