#!/bin/bash
#
# 13-pi-tweaks — optional Raspberry Pi hardware tweaks (Wi-Fi/Bluetooth off, HDMI off).
#
# Pi-specific (aarch64), entirely opt-in (every prompt defaults to N). On a
# headless audio host these cut RF noise and background activity:
#
#   A. Disable the onboard Wi-Fi + Bluetooth radios. Primary, reliable method:
#      use 'install <mod> /bin/false' directives in /etc/modprobe.d for every
#      Wi-Fi/BT module (brcmfmac, brcmutil, btbcm, hci_uart, btsdio, bluetooth)
#      and rebuild the initramfs so the directives are honoured at boot.
#      We do NOT use 'blacklist': on the Pi 5, Bluetooth (btsdio) is bound via
#      a device-tree entry which bypasses the blacklist mechanism entirely —
#      a pure blacklist leaves the radios active after reboot (bug reported by
#      Auke 2026-06-17). The 'install … /bin/false' override intercepts the
#      module load at the kernel module layer regardless of how it was
#      triggered (udev, device-tree, manual modprobe). Also rfkill-blocks them
#      now, and — best-effort — adds the disable-wifi/disable-bt dtoverlays
#      if a Pi config.txt is found (Fedora's firmware-partition layout varies,
#      so this is secondary).
#
#   B. Disable HDMI video output via the kernel cmdline (video=HDMI-A-*:d, set
#      with grubby). Headless hosts only — there is NO console video afterwards.
#
# All changes are reversible (the module prints how). UNTESTED on hardware: the
# module blacklist and the kernel cmdline are the dependable parts; the
# config.txt dtoverlay is best-effort. ARM-only — not shipped in the x86 repo.
#

set -euo pipefail

readonly _PT_MODPROBE="/etc/modprobe.d/99-audiophile-disable-radios.conf"
readonly _PT_GEN_TAG="# Generated by fedora-audiophile-setup"
readonly _PT_HDMI_ARGS="video=HDMI-A-1:d video=HDMI-A-2:d"

log_step "Raspberry Pi hardware tweaks (optional) — Wi-Fi/Bluetooth off, HDMI off"

if ! ask_yes_no "Apply optional Raspberry Pi hardware tweaks (radios off / HDMI off)?" N PI_TWEAKS; then
    log_info "Skipping Pi hardware tweaks."
    return 0 2>/dev/null || exit 0
fi

# Echo the first existing Pi config.txt path, or nothing. Fedora may mount the
# firmware FAT partition at /boot/efi; Pi OS uses /boot/firmware or /boot.
_pt_find_configtxt() {
    local p
    for p in /boot/efi/config.txt /boot/firmware/config.txt /boot/config.txt; do
        [[ -f "$p" ]] && { echo "$p"; return 0; }
    done
}

# --- A. Wi-Fi + Bluetooth off --------------------------------------------

if ask_yes_no "  → Disable onboard Wi-Fi + Bluetooth? (wired LAN required)" N PI_TWEAKS_WIFI_BT; then
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write ${_PT_MODPROBE} (install /bin/false on brcmfmac/brcmutil/btbcm/hci_uart/btsdio/bluetooth), rebuild initramfs (dracut -f), rfkill-block, and add disable-wifi/disable-bt to a config.txt if found."
    else
        log_info "Disabling Wi-Fi/Bluetooth kernel module autoload via ${_PT_MODPROBE}"
        cat > "$_PT_MODPROBE" <<EOF
${_PT_GEN_TAG}
# Disable the Raspberry Pi onboard Wi-Fi and Bluetooth radios (audiophile host
# on a wired LAN). 'install <mod> /bin/false' intercepts the module load at the
# kernel-module layer no matter what triggered it — udev, device-tree, manual
# modprobe. A 'blacklist' directive would silently miss btsdio (the Pi 5 BT
# module is bound via device-tree, which bypasses blacklist entirely — Auke
# bug report 2026-06-17). To undo: remove this file, then 'sudo dracut -f'
# and reboot.
install brcmfmac  /bin/false
install brcmutil  /bin/false
install btbcm     /bin/false
install hci_uart  /bin/false
install btsdio    /bin/false
install bluetooth /bin/false
EOF
        # The directives must be baked into the initramfs to apply at boot
        # (brcmfmac would otherwise load early). dracut -f rebuilds it.
        log_info "Rebuilding the initramfs so the directives apply at boot (dracut -f)."
        run_cmd dracut -f

        # Immediate effect this session (best-effort).
        if command -v rfkill >/dev/null 2>&1; then
            run_cmd rfkill block wifi || true
            run_cmd rfkill block bluetooth || true
        fi

        # Best-effort firmware-level overlay (secondary to the blacklist).
        _pt_cfg=$(_pt_find_configtxt)
        if [[ -n "${_pt_cfg:-}" ]]; then
            _pt_added=0
            grep -q '^dtoverlay=disable-wifi' "$_pt_cfg" || { echo 'dtoverlay=disable-wifi' >> "$_pt_cfg"; _pt_added=1; }
            grep -q '^dtoverlay=disable-bt'   "$_pt_cfg" || { echo 'dtoverlay=disable-bt'   >> "$_pt_cfg"; _pt_added=1; }
            [[ "$_pt_added" -eq 1 ]] && log_info "Added disable-wifi/disable-bt dtoverlay to ${_pt_cfg} (firmware-level, next boot)."
        else
            log_info "No Pi config.txt found (checked /boot/efi, /boot/firmware, /boot) — the module blacklist is what does the work."
        fi
        log_info "Wi-Fi/Bluetooth disabled. Full effect after the next reboot."
    fi
fi

# --- B. HDMI output off --------------------------------------------------

if ask_yes_no "  → Disable HDMI video output? (HEADLESS only — no console video after this)" N PI_TWEAKS_HDMI; then
    log_warn "HDMI output will be disabled at the kernel level — you will have NO console display after reboot."
    log_warn "Only do this on a host you can fully administer over SSH."
    log_warn "To undo later: sudo grubby --update-kernel=ALL --remove-args=\"${_PT_HDMI_ARGS}\" ; then reboot."
    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would add '${_PT_HDMI_ARGS}' to the kernel cmdline via grubby."
    elif grep -qw 'video=HDMI-A-1:d' /proc/cmdline 2>/dev/null \
            || grubby --info=ALL 2>/dev/null | grep -q 'video=HDMI-A-1:d'; then
        log_info "HDMI-off kernel args already present — skipping."
    else
        log_info "Adding '${_PT_HDMI_ARGS}' to all kernel entries via grubby."
        run_cmd grubby --update-kernel=ALL --args="${_PT_HDMI_ARGS}"
        log_info "HDMI output will be off at next boot."
    fi
fi

log_info "Pi hardware tweaks complete."
