#!/bin/bash
#
# 14-ram-mode — RAM-mode: full-root-in-RAM via overlayfs or systemd.volatile.
#
# PART A — Analysis (always runs, no changes):
#   Reports RAM total, root FS used, headroom, top 10 largest dirs.
#
# PART B — Interactive menu:
#   E) Enable  — choose volatile or overlayfs
#   D) Disable — revert every artefact this module created
#   N) Skip
#
# Strategy V — systemd.volatile=state:
#   /var is copied into a tmpfs during initrd. /etc and / stay on disk and
#   are idle after boot. Writes to /var are lost on reboot.
#   /etc edits are always persistent (disk).
#
# Strategy O — overlayfs:
#   The real root is mounted read-only as the lower layer; a tmpfs upper
#   layer catches all writes. The disk is truly idle after boot.
#   ALL writes (including /etc) are in RAM and lost on reboot.
#   There is no in-session way to make a change permanent.
#   To make a permanent change: Disable, reboot, edit on the disk-backed
#   root normally, then Enable again.
#
# Revert:
#   Removes all artefacts: cmdline params, dracut conf, dracut module dir,
#   recovery GRUB entries. Rebuilds initramfs. Effective after next reboot.
#
# Credits:
#   Overlayfs strategy, dracut module, bind-mount architecture, BLS-aware
#   grubby revert — originally developed by Auke Dijkstra for this wizard.
#

set -euo pipefail

if [[ -z "${_RAM_GEN_TAG+_}" ]]; then
    readonly _RAM_GEN_TAG="# Generated by fedora-audiophile-setup"
    readonly _RAM_DRACUT_CONF="/etc/dracut.conf.d/99-audiophile-ram-overlay.conf"
    # On Fedora both /usr/lib/dracut/modules.d/ and /lib/dracut/modules.d/
    # exist (the latter is a symlink to the former). Install there directly
    # so dracut finds the module without any modulesdir workaround.
    readonly _RAM_DRACUT_MODULE_BASE="/usr/lib/dracut/modules.d"
    readonly _RAM_DRACUT_MODULE_DIR="${_RAM_DRACUT_MODULE_BASE}/99audiophile-overlay"
    readonly _RAM_VOLATILE_PARAM="systemd.volatile=state"
    readonly _RAM_OVERLAY_PARAM="audiophile.overlay=1"
    readonly _RAM_BIND_SCRIPT="/usr/local/sbin/audiophile-overlay-bind.sh"

    # --- LEGACY: persist-via-service mechanism, retired. _ram_enable_overlay
    # no longer creates this service — these two constants exist ONLY so
    # _ram_do_disable can clean up leftovers on installs that predate this.
    # There is currently NO automatic persistence mechanism for overlay mode.
    # The only supported way to make a permanent change is:
    # Disable, reboot, edit on the disk-backed root, Enable again.
    readonly _RAM_PERSIST_SVC_NAME="audiophile-overlay-persist.service"
    readonly _RAM_PERSIST_SVC_PATH="/etc/systemd/system/${_RAM_PERSIST_SVC_NAME}"
fi

log_step "RAM-mode (analysis / enable / disable)"

# =========================================================================
# PART A: Analysis
# =========================================================================

log_info "---- System RAM-fit analysis ----"

_ram_total_kb=$(awk '/^MemTotal:/{print $2}' /proc/meminfo)
_ram_available_kb=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
_ram_total_mb=$(( _ram_total_kb / 1024 ))
_ram_available_mb=$(( _ram_available_kb / 1024 ))
_rootfs_used_mb=$(df --output=used -BM / | tail -1 | tr -d 'M[:space:]')
_rootfs_size_mb=$(df --output=size -BM / | tail -1 | tr -d 'M[:space:]')
_headroom_mb=$(( _ram_total_mb - _rootfs_used_mb ))
_overhead_mb=$(( _ram_total_mb - _ram_available_mb ))

log_info "RAM total    : ${_ram_total_mb} MiB"
log_info "RAM available: ${_ram_available_mb} MiB  (free + reclaimable)"
log_info "Root FS used : ${_rootfs_used_mb} MiB  (of ${_rootfs_size_mb} MiB)"
log_info "Kernel overhead (current): ${_overhead_mb} MiB"
log_info "Headroom if root in RAM  : ${_headroom_mb} MiB"

if (( _headroom_mb >= 256 )); then
    log_info "Assessment: FITS — ${_headroom_mb} MiB headroom. RAM-mode is feasible."
    _ram_fits=1
elif (( _headroom_mb >= 64 )); then
    log_warn "Assessment: TIGHT — ${_headroom_mb} MiB headroom. Possible but risky."
    _ram_fits=1
else
    log_warn "Assessment: DOES NOT FIT — ${_headroom_mb} MiB headroom. OOM likely."
    _ram_fits=0
fi

log_info "Top 10 largest directories under / (excluding /proc /sys /dev /run):"
du -mx --max-depth=2 / \
    --exclude=/proc --exclude=/sys --exclude=/dev --exclude=/run \
    2>/dev/null \
    | sort -rn | head -10 \
    | while IFS=$'\t' read -r size path; do
        log_info "  ${size} MiB  ${path}"
      done || true

log_info "---- End of analysis ----"

# =========================================================================
# Helpers
# =========================================================================

_ram_grubby_args() {
    grubby --info DEFAULT 2>/dev/null \
        | grep '^args=' | head -1 \
        | sed 's/^args="//; s/"$//'
}

_ram_grubby_initrd() {
    grubby --info DEFAULT 2>/dev/null \
        | grep '^initrd=' | head -1 \
        | sed 's/^initrd=//'
}

_ram_current_mode() {
    local args
    args=$(_ram_grubby_args)
    if   [[ "$args" == *"$_RAM_VOLATILE_PARAM"* ]]; then echo "volatile"
    elif [[ "$args" == *"$_RAM_OVERLAY_PARAM"*  ]]; then echo "overlay"
    else                                                   echo "none"
    fi
}

# Add a recovery GRUB entry (copy of DEFAULT, without $1 in args).
# Skips silently if an entry with the same title already exists.
_ram_add_recovery_entry() {
    local strip_param="$1" title="$2"
    if grubby --info ALL 2>/dev/null | grep -q "title=\"${title}\""; then
        log_info "Recovery entry '${title}' already exists — skipping."
        return 0
    fi
    local kernel initrd args_clean
    kernel=$(grubby --default-kernel 2>/dev/null || true)
    [[ -n "$kernel" && -f "$kernel" ]] \
        || { log_warn "Cannot locate default kernel — recovery entry skipped."; return 0; }
    initrd=$(_ram_grubby_initrd)
    args_clean=$(_ram_grubby_args | sed "s/${strip_param}//g" | xargs)
    run_cmd grubby --add-kernel="$kernel" \
        --title="$title" \
        ${initrd:+--initrd="$initrd"} \
        --args="${args_clean}" \
        || log_warn "grubby --add-kernel failed — recovery entry not created."
    log_info "Recovery GRUB entry created: '${title}'"
}

# Remove every recovery GRUB/BLS entry matching the given title.
#
# Why id-based: grubby --info=ALL can list several entries that all point
# at the same kernel path (e.g. every "Fedora RT (recovery — no overlay)"
# entry created across repeated enable/disable cycles, plus the real boot
# entry itself). Removing by kernel path is therefore ambiguous and, with
# grubby's quoted output, title=/kernel= scraping left the surrounding
# quote characters in the path — so --remove-kernel never matched anything
# and stale entries silently piled up.
#
# 'id=' is the one field that uniquely identifies a BLS entry — it is the
# entry's filename (/boot/loader/entries/<id>.conf). We match on that and
# delete the file directly, which also avoids relying on grubby parsing
# its own ambiguous kernel-path match. Loops over ALL matches, not just
# the first, so previously-orphaned duplicates get cleaned up too.
_ram_remove_recovery_entries() {
    local title="$1" _found_any=0
    local entries
    entries=$(grubby --info=ALL 2>/dev/null | awk '
        function emit() { if (title != "" && id != "") print id "\t" title "\t" kernel }
        BEGIN { title=""; id=""; kernel="" }
        /^index=/ { emit(); title=""; id=""; kernel="" }
        /^title=/ { t=$0; sub(/^title=/,"",t); gsub(/^"|"$/,"",t); title=t }
        /^id=/    { t=$0; sub(/^id=/,"",t); gsub(/^"|"$/,"",t); id=t }
        /^kernel=/{ t=$0; sub(/^kernel=/,"",t); gsub(/^"|"$/,"",t); kernel=t }
        END { emit() }
    ' || true)

    local entry_id entry_title entry_kernel
    while IFS=$'\t' read -r entry_id entry_title entry_kernel; do
        [[ -z "$entry_id" ]] && continue
        [[ "$entry_title" == "$title" ]] || continue
        _found_any=1

        if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
            log_info "DRY-RUN: would remove recovery entry '${title}' (id=${entry_id})."
            continue
        fi

        local bls_file="/boot/loader/entries/${entry_id}.conf"
        if [[ -f "$bls_file" ]]; then
            if rm -f "$bls_file"; then
                log_info "Removed recovery entry '${title}' (${bls_file})."
            else
                log_warn "Failed to remove ${bls_file}."
            fi
        else
            # Non-BLS fallback (legacy grub.cfg). Best-effort only.
            if run_cmd grubby --remove-kernel="$entry_kernel"; then
                log_info "Removed recovery entry '${title}' via grubby (kernel=${entry_kernel})."
            else
                log_warn "grubby --remove-kernel failed for '${title}' (kernel=${entry_kernel})."
            fi
        fi
    done <<< "$entries"

    [[ "$_found_any" -eq 1 ]]
}

# =========================================================================
# Menu
# =========================================================================

_current_mode=$(_ram_current_mode)
log_info "Current RAM mode: ${_current_mode}"
echo
log_info "What would you like to do?"
log_info "  E) Enable  RAM mode"
log_info "  D) Disable RAM mode (revert all artefacts from this module)"
log_info "  N) Skip"
echo

_ram_action="$(resolve_input RAM_MODE_ACTION "    Choice [e/d/N]:")"
_ram_action="${_ram_action:-N}"

case "${_ram_action^^}" in
    N) log_info "Skipping."; return 0 2>/dev/null || exit 0 ;;
    E) ;;
    D) ;;
    *) log_error "Invalid choice '${_ram_action}'."; exit 1 ;;
esac

# =========================================================================
# ENABLE — volatile
# =========================================================================

_ram_enable_volatile() {
    local current_args _ram_volatile_cmdline_already_set=0
    current_args=$(_ram_grubby_args)

    if [[ "$current_args" == *"$_RAM_VOLATILE_PARAM"* ]]; then
        log_info "systemd.volatile=state already in cmdline — will still verify"
        log_info "configuration is consistent; cmdline and recovery entry left as-is."
        _ram_volatile_cmdline_already_set=1
    fi

    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would add '${_RAM_VOLATILE_PARAM}' and create recovery entry."
        return 0
    fi

    if [[ "$_ram_volatile_cmdline_already_set" -eq 1 ]]; then
        log_info "Kernel cmdline already had '${_RAM_VOLATILE_PARAM}' — left as-is."
        log_info "Recovery entry was created on first enable; not duplicating it."
    else
        _ram_add_recovery_entry "$_RAM_VOLATILE_PARAM" "Fedora RT (recovery — no RAM mode)"
        run_cmd grubby --update-kernel=DEFAULT --args="$_RAM_VOLATILE_PARAM"
    fi

    log_info "volatile RAM mode enabled."
    log_info "After reboot verify: findmnt -n -o FSTYPE /var   # should print 'tmpfs'"
    log_info "/var changes are not persisted automatically — they're lost on reboot."
    log_info "To make a permanent /var-related change: Disable, reboot, edit on disk, Enable again."
}

# =========================================================================
# ENABLE — overlayfs
#
# Why lowerdir is a separate bind-mount, not $NEWROOT directly:
#   The real disk root is bind-mounted to /run/audiophile-overlay-ram/lower
#   BEFORE the overlay is mounted, and that bind-mount path — not $NEWROOT
#   itself — is used as the overlay's lowerdir. /run survives switch_root,
#   so /run/audiophile-overlay-ram/lower remains a valid, reachable
#   directory pointing at the real disk content after the pivot — useful for
#   manual inspection/recovery (e.g. `ls /run/audiophile-overlay-ram/lower`
#   while live). Nothing automated currently relies on this path; there is
#   no automatic persistence mechanism for overlay mode. The only supported
#   way to make a permanent change is: Disable, reboot, edit on the
#   disk-backed root, Enable again.
#
#   NOTE: an earlier version used lowerdir=$NEWROOT directly — i.e. the
#   overlay's own mountpoint as its own lower source. That self-shadows:
#   once mounted, the path $NEWROOT resolves to the overlay, not the
#   original disk mount, so the recorded lowerdir became unreachable after
#   switch_root even though the overlay itself worked fine for normal use.
#   Keep using a separate bind-mounted path, never the overlay's own
#   mountpoint, as lowerdir.
# =========================================================================

_ram_enable_overlay() {
    local current_args _ram_cmdline_already_set=0
    current_args=$(_ram_grubby_args)

    if [[ "$current_args" == *"$_RAM_OVERLAY_PARAM"* ]]; then
        log_info "audiophile.overlay=1 already in cmdline — will still"
        log_info "(re)write the dracut module/service and rebuild initramfs,"
        log_info "in case the module on disk is stale or was never built in."
        _ram_cmdline_already_set=1
    fi

    if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
        log_info "DRY-RUN: would write dracut module, run dracut -f, add recovery entry, update cmdline."
        return 0
    fi

    # --- dracut module ---
    mkdir -p "$_RAM_DRACUT_MODULE_DIR"

    cat > "${_RAM_DRACUT_MODULE_DIR}/module-setup.sh" <<'MODEOF'
#!/bin/bash
check()   { return 0; }
depends() { echo "base"; }
install() {
    inst_script "$moddir/audiophile-overlay-mount.sh" /usr/bin/audiophile-overlay-mount.sh
    inst_simple "$moddir/audiophile-overlay.service" \
        "${systemdsystemunitdir}/audiophile-overlay.service"
    mkdir -p "${initdir}${systemdsystemunitdir}/initrd-root-fs.target.wants"
    ln -sf ../audiophile-overlay.service \
        "${initdir}${systemdsystemunitdir}/initrd-root-fs.target.wants/audiophile-overlay.service"
    instmods overlay
}
MODEOF
    chmod +x "${_RAM_DRACUT_MODULE_DIR}/module-setup.sh"

    # Mount script: wraps the real root in overlayfs before pivot_root.
    # Dracut 108+ uses systemd in the initrd; shell mount hooks are no longer
    # called. Hence we use a systemd service in the initramfs instead.
    # Scratch dir is under /run/ (outside NEWROOT) so it is not shadowed by
    # the overlay itself. The real root is FIRST bind-mounted to scratch/lower,
    # and THAT path — not NEWROOT itself — is used as lowerdir; otherwise
    # lowerdir becomes unreachable after switch_root (self-shadowing; see the
    # architecture note above). awk is not available in the initramfs; use
    # shell-native /proc/meminfo parsing.
    cat > "${_RAM_DRACUT_MODULE_DIR}/audiophile-overlay-mount.sh" <<'HOOKEOF'
#!/bin/bash
type getarg >/dev/null 2>&1 || . /lib/dracut-lib.sh

getargbool 0 audiophile.overlay || exit 0

NEWROOT="${NEWROOT:-/sysroot}"

# Shell-native /proc/meminfo parsing (awk not available in initramfs)
while IFS=": " read -r key val _; do
    [[ "$key" == "MemTotal" ]] && ram_kb=$val && break
done < /proc/meminfo

tmpfs_mb=$(( ram_kb / 1024 - 128 ))
[[ $tmpfs_mb -lt 128 ]] && tmpfs_mb=128

scratch="/run/audiophile-overlay-ram"
mkdir -p "$scratch"
mount -t tmpfs -o "size=${tmpfs_mb}m,mode=0755" audiophile-overlay-ram "$scratch"
mkdir -p "${scratch}/upper" "${scratch}/work" "${scratch}/lower"

mount -o remount,ro "$NEWROOT"

# Bind-mount the real (lower) root onto a path under /run BEFORE overlaying
# $NEWROOT. /run survives switch_root, but $NEWROOT itself gets shadowed
# the instant the overlay mounts on top of it: a lowerdir= equal to
# $NEWROOT becomes an unreachable path after the pivot (the kernel still
# holds the mount, but no path resolves to it anymore) — even though the
# overlay itself works fine for normal use. Binding the real root
# elsewhere first keeps it reachable post-boot for manual inspection.
mount --bind "$NEWROOT" "${scratch}/lower"

# systemd marks / as a SHARED mount early in boot (mount --make-rshared /)
# for namespace propagation. Binding a shared mount makes the new bind
# copy a PEER in that same propagation group — so the overlay mount we're
# about to create on $NEWROOT would otherwise propagate automatically
# onto our bind copy too, silently re-stacking the overlay on top of
# itself at ${scratch}/lower. That defeats the entire point of this bind
# (having an independent, guaranteed-real path to the disk content) even
# though reads through it would still happen to resolve correctly (the
# overlay falls through to its own lowerdir, which bottoms out on the
# real XFS mount regardless). Making this mount private detaches it from
# the peer group so later mounts on $NEWROOT do not propagate here.
mount --make-private "${scratch}/lower"

mount -t overlay overlay \
    -o "lowerdir=${scratch}/lower,upperdir=${scratch}/upper,workdir=${scratch}/work" \
    "$NEWROOT"
HOOKEOF
    chmod +x "${_RAM_DRACUT_MODULE_DIR}/audiophile-overlay-mount.sh"

    # Systemd service for the initramfs (required for dracut 108+ with systemd initrd)
    cat > "${_RAM_DRACUT_MODULE_DIR}/audiophile-overlay.service" <<'SVCEOF'
[Unit]
Description=Audiophile overlayfs RAM mount
DefaultDependencies=no
After=sysroot.mount
Before=initrd-root-fs.target
ConditionKernelCommandLine=audiophile.overlay=1

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/audiophile-overlay-mount.sh

[Install]
WantedBy=initrd-root-fs.target
SVCEOF

    cat > "$_RAM_DRACUT_CONF" <<EOF
${_RAM_GEN_TAG}
# Include the audiophile-overlay module in every future initramfs build.
add_dracutmodules+=" audiophile-overlay "
EOF

    log_info "Rebuilding initramfs (dracut -f)..."
    # Call dracut directly — the wizard pipes run_cmd through tee to the
    # log file; if LOG_FILE is unset, tee fails and dracut never runs.
    dracut -f || { log_error "dracut -f failed (exit $?) — initramfs not rebuilt."; exit 1; }
    log_info "initramfs rebuilt successfully."

    if [[ "$_ram_cmdline_already_set" -eq 1 ]]; then
        log_info "Kernel cmdline already had '${_RAM_OVERLAY_PARAM}' — left as-is."
        log_info "Recovery entry was created on first enable; not duplicating it."
    else
        _ram_add_recovery_entry "audiophile\\.overlay=1" "Fedora RT (recovery — no overlay)"
        run_cmd grubby --update-kernel=DEFAULT --args="audiophile.overlay=1"
    fi

    log_info "overlayfs RAM mode enabled."
    log_warn "All writes (including /etc) are in RAM and lost on reboot."
    echo
    log_step "Persistence — read this before making changes"
    log_info "There is no in-session way to make a change permanent. Any edit"
    log_info "(installing packages, editing /etc, adding files) exists only in"
    log_info "RAM and is gone after reboot."
    log_info ""
    log_info "To make a permanent change:"
    log_info "  1. Disable RAM mode:  sudo ./setup.sh --only ram-mode  (choose D)"
    log_info "  2. Reboot — you're back on the real disk-backed root"
    log_info "  3. Make your change normally (dnf install, edit /etc/..., etc.)"
    log_info "  4. Enable RAM mode again if you want it back:  choose E"
    echo
    log_info "After reboot verify:"
    log_info "  findmnt -n -o FSTYPE /              # overlay"
    log_info "  touch /etc/test && echo OK && rm /etc/test   # writable (in RAM only)"
}

# =========================================================================
# ENABLE dispatch
# =========================================================================

_ram_do_enable() {
    if [[ "$_ram_fits" -eq 0 ]]; then
        log_warn "RAM-mode enable skipped: root FS does not fit in RAM."
        return 0
    fi

    echo
    log_info "Two strategies:"
    log_info "  V) volatile  — /var in RAM; /etc persistent on disk. Lightest."
    log_info "  O) overlayfs — full root in RAM; all writes in RAM, lost on reboot."
    log_info "                 To make a permanent change: Disable, reboot, edit, Enable."
    echo
    _strat="$(resolve_input RAM_MODE_STRATEGY "    Strategy [o/V]:")"
    _strat="${_strat:-V}"

    case "${_strat^^}" in
        V) _ram_strategy="volatile" ;;
        O) _ram_strategy="overlay"  ;;
        *) log_error "Invalid: expected V or O."; exit 1 ;;
    esac

    log_warn "This modifies the boot process. Physical console access recommended."
    log_warn "A recovery GRUB entry will be created so you can always roll back."
    if ! ask_yes_no "Enable RAM-mode (${_ram_strategy})?" N RAM_MODE_ENABLE; then
        log_info "Cancelled."; return 0
    fi

    case "$_ram_strategy" in
        volatile) _ram_enable_volatile ;;
        overlay)  _ram_enable_overlay  ;;
    esac
}

# =========================================================================
# DISABLE / REVERT
# =========================================================================

_ram_do_disable() {
    log_step "Disable RAM mode — reverting all artefacts"

    local current_args changed=0
    current_args=$(_ram_grubby_args)

    # 1. Remove cmdline params
    for param in "$_RAM_VOLATILE_PARAM" "audiophile.overlay"; do
        if [[ "$current_args" == *"$param"* ]]; then
            if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
                log_info "DRY-RUN: would remove '${param}' from cmdline."
            else
                run_cmd grubby --update-kernel=DEFAULT --remove-args="$param"
                log_info "Removed '${param}' from kernel cmdline."
            fi
            changed=1
        fi
    done

    # 2. Remove dracut conf + module, rebuild initramfs
    local dracut_changed=0
    if [[ -f "$_RAM_DRACUT_CONF" ]]; then
        if [[ "${DRY_RUN:-0}" -ne 1 ]]; then
            rm -f "$_RAM_DRACUT_CONF"
            log_info "Removed ${_RAM_DRACUT_CONF}."
        else
            log_info "DRY-RUN: would remove ${_RAM_DRACUT_CONF}."
        fi
        dracut_changed=1; changed=1
    fi
    if [[ -d "$_RAM_DRACUT_MODULE_DIR" ]]; then
        if [[ "${DRY_RUN:-0}" -ne 1 ]]; then
            rm -rf "$_RAM_DRACUT_MODULE_DIR"
            # Remove the base dir too if it is now empty.
            rmdir "$_RAM_DRACUT_MODULE_BASE" 2>/dev/null || true
            log_info "Removed dracut module dir."
        else
            log_info "DRY-RUN: would remove ${_RAM_DRACUT_MODULE_DIR}."
        fi
        dracut_changed=1; changed=1
    fi
    if [[ "$dracut_changed" -eq 1 && "${DRY_RUN:-0}" -ne 1 ]]; then
        dracut -f || { log_error "dracut -f failed (exit $?) — initramfs not rebuilt."; exit 1; }
        log_info "Initramfs rebuilt (overlay module removed)."
    fi

    # 3. Remove bind helper script (legacy artefact)
    if [[ -f "$_RAM_BIND_SCRIPT" ]]; then
        if [[ "${DRY_RUN:-0}" -ne 1 ]]; then
            rm -f "$_RAM_BIND_SCRIPT"
            log_info "Removed bind helper script ${_RAM_BIND_SCRIPT}."
        else
            log_info "DRY-RUN: would remove ${_RAM_BIND_SCRIPT}."
        fi
        changed=1
    fi

    # 4. Remove persist service (legacy artefact)
    if [[ -f "$_RAM_PERSIST_SVC_PATH" ]]; then
        if [[ "${DRY_RUN:-0}" -eq 1 ]]; then
            log_info "DRY-RUN: would disable and remove ${_RAM_PERSIST_SVC_PATH}."
        else
            run_cmd systemctl disable "$_RAM_PERSIST_SVC_NAME" 2>/dev/null || true
            rm -f "$_RAM_PERSIST_SVC_PATH"
            run_cmd systemctl daemon-reload
            log_info "Removed persist service."
        fi
        changed=1
    fi

    # 5. Remove recovery GRUB entries
    local recovery_titles=(
        "Fedora RT (recovery — no RAM mode)"
        "Fedora RT (recovery — no overlay)"
    )
    for title in "${recovery_titles[@]}"; do
        if _ram_remove_recovery_entries "$title"; then
            changed=1
        fi
    done

    if [[ "$changed" -eq 0 ]]; then
        log_info "Nothing to revert — no RAM-mode artefacts found."
    else
        log_info "RAM mode disabled. Reboot to return to normal disk boot."
    fi
}

# =========================================================================
# Dispatch
# =========================================================================

case "${_ram_action^^}" in
    E) _ram_do_enable  ;;
    D) _ram_do_disable ;;
esac
